### ISSUE TITLE
No pages in this database

### ISSUE THREAD

**Issue by ilyasni** [ryonakae/figma-plugin-sync-notion#12]
Hi!
I did everything according to the instructions, created an integration, linked it to a table and specified the key and value columns.
When trying to connect in figma, an error appears — "No pages in this database". What could be the problem?

**Comment by perrinebo** [comment]
Hi,
are you sure you are in a database?
I had the same error today, but I was in a page (with a database in it) not a database.

The URL from a database look like this :
"https://www.notion.so/**databaseKEY**?v=bf28t89rt2794c7bda7re186z17704b5"
